# Generated by Django 4.1.3 on 2022-11-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_userprofile_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/default/man-156584_960_720.webp', null=True, upload_to='userprofile'),
        ),
    ]
